// Shared staging helpers for catalog agent verification (rungs 2-4).
//
// Catalog agents are copied OUT of the repo before anything installs or
// builds, so npm/eve artifacts never land inside catalog/agents/ and the
// module graph we verify matches what a real consumer gets (no pnpm
// workspace hoisting, no parent lockfile interference).
//
// The staging root defaults to ../eve-directory-test (a plain sibling
// folder of the repo — intentionally NOT a git repo or pnpm workspace).
// CI overrides it with EVE_STAGE_DIR=<temp dir>. Everything under the
// staging root is generated: scripts wipe and re-stage on every run.

import { execFile } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

export const REPO_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  ".."
);

export const AGENTS_ROOT = path.join(REPO_ROOT, "catalog", "agents");

export const CLEAN_DIAGNOSTICS = /Diagnostics\s+0 errors, 0 warnings/;

// Build artifacts that never travel from the repo into a staged copy.
// rsync also protects these on the destination (no --delete-excluded),
// so a staged node_modules survives re-staging and repeat runs stay fast.
const STAGE_EXCLUDES = [
  "node_modules/",
  ".eve/",
  ".output/",
  ".cache/",
  "var/",
];

const STAGE_README = `# eve-directory-test

Generated by \`eve-directory/scripts/\`. **Never edit anything in here by hand.**

Every run of \`pnpm agents:check\`, \`pnpm agents:eval\`, or \`pnpm registry:smoke\`
wipes and re-stages the directories it touches. Hand edits are lost on the next
run — make changes in \`eve-directory/catalog/agents/<slug>/\` instead.

Layout:

- \`staged/<slug>/\` — fresh copies of catalog agents; \`node_modules/\` and \`.eve/\`
  build artifacts live here instead of inside the repo
- \`consumers/<slug>/\` — scratch projects for \`pnpm registry:smoke\`
  (shadcn install path verification)

The whole folder is disposable: delete it any time, scripts recreate it.
`;

export function stageRoot() {
  return process.env.EVE_STAGE_DIR
    ? path.resolve(REPO_ROOT, process.env.EVE_STAGE_DIR)
    : path.resolve(REPO_ROOT, "..", "eve-directory-test");
}

async function ensureStageRoot() {
  const root = stageRoot();
  await mkdir(root, { recursive: true });
  const readmePath = path.join(root, "README.md");
  if (!existsSync(readmePath)) {
    await writeFile(readmePath, STAGE_README, "utf-8");
  }
  return root;
}

/** Copy catalog/agents/<slug>/ into <stage>/staged/<slug>/ and return that path. */
export async function stageAgent(slug) {
  const source = path.join(AGENTS_ROOT, slug);
  const stagedDir = path.join(await ensureStageRoot(), "staged", slug);
  await mkdir(stagedDir, { recursive: true });

  const args = [
    "--archive",
    "--delete",
    ...STAGE_EXCLUDES.flatMap((pattern) => ["--exclude", pattern]),
    `${source}/`,
    `${stagedDir}/`,
  ];
  await execFileAsync("rsync", args);

  return stagedDir;
}

/** Wipe and recreate <stage>/consumers/<slug>/; returns the empty dir. */
export async function freshConsumerDir(slug) {
  const consumerDir = path.join(await ensureStageRoot(), "consumers", slug);
  await execFileAsync("rm", ["-rf", consumerDir]);
  await mkdir(consumerDir, { recursive: true });
  return consumerDir;
}

/**
 * Secrets for staged runs (AI_GATEWAY_API_KEY for eve eval) live in
 * <stage root>/.env.local — outside the repo, never copied into staged
 * dirs. Returns the parsed key/value pairs, or {} when absent.
 */
export async function stageEnv() {
  const envPath = path.join(stageRoot(), ".env.local");
  if (!existsSync(envPath)) return {};

  const env = {};
  for (const line of (await readFile(envPath, "utf-8")).split("\n")) {
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (!match) continue;
    env[match[1]] = match[2].replace(/^(["'])(.*)\1$/, "$2");
  }
  return env;
}

export async function listAgentDirs() {
  const entries = await readdir(AGENTS_ROOT);
  const dirs = [];
  for (const entry of entries) {
    const fullPath = path.join(AGENTS_ROOT, entry);
    if ((await stat(fullPath)).isDirectory()) dirs.push(entry);
  }
  return dirs.sort();
}

/** Validate requested slugs against catalog/agents/; exits on unknown. */
export async function resolveTargets(requested) {
  const available = await listAgentDirs();
  const unknown = requested.filter((slug) => !available.includes(slug));
  if (unknown.length > 0) {
    console.error(`Unknown agent slug(s): ${unknown.join(", ")}`);
    console.error(`Available: ${available.join(", ")}`);
    process.exit(1);
  }
  return requested.length > 0 ? requested : available;
}

/** Run a command, capturing combined output; never throws. */
export async function run(command, args, cwd, timeout, extraEnv = {}) {
  try {
    const { stdout, stderr } = await execFileAsync(command, args, {
      cwd,
      timeout,
      maxBuffer: 10 * 1024 * 1024,
      env: { ...process.env, NO_COLOR: "1", ...extraEnv },
    });
    return { ok: true, output: `${stdout}\n${stderr}` };
  } catch (error) {
    const output = `${error.stdout ?? ""}\n${error.stderr ?? ""}`.trim();
    return { ok: false, output: output || error.message };
  }
}
